let manifest=null,questions=[],sourceQuestions=[],current=0,sessionScore=0,answers={},mode='practice',flagged=new Set(),favorites=new Set(),appView='academy',activePackFile='',examBank=[];
const EXAM_PACKS=['questions/exam-sim-v2-batch1.json','questions/exam-sim-v2-batch2.json'];
const EXAM_PACK=EXAM_PACKS.join('+');
const STORE='cysaCoachR3Stats', LISTS='cysaCoachR3Lists';
const CASE_DETAILS={
'Case 001':{number:'Case File 001',title:'Payroll Phishing Campaign',difficulty:'Hard',scenario:'A payroll specialist opened a password-protected attachment from an external sender. Endpoint telemetry shows suspicious Microsoft Word and PowerShell behavior, but containment decisions must be based on validated impact.',context:'Correlate endpoint, email, DNS, and proxy evidence to determine execution, scope, containment, and leadership communication.'},
'Case 002':{number:'Case File 002',title:'VPN Authentication Bypass',difficulty:'Hard',scenario:'An internet-facing VPN appliance has an authentication bypass vulnerability with public exploit code and active exploitation reported by threat intelligence.',context:'Prioritize remediation using exposure, exploitability, business criticality, detection evidence, containment options, and stakeholder communication.'},
'Case 003':{number:'Case File 003',title:'Ransomware Outbreak',difficulty:'Hard',scenario:'A ransomware incident is unfolding across business systems, requiring careful incident response sequencing and evidence-based scoping.',context:'Identify first actions, patient-zero evidence, eradication steps, executive messaging, and correct response sequence.'}
};
function getStats(){return JSON.parse(localStorage.getItem(STORE)||'{"answered":0,"correct":0,"lowConf":0,"domains":{},"topics":{},"mistakes":{}}')}
function getLists(){return JSON.parse(localStorage.getItem(LISTS)||'{"flagged":[],"incorrect":[],"favorites":[]}' )}
function saveLists(l){localStorage.setItem(LISTS,JSON.stringify(l))}
function saveStats(s){localStorage.setItem(STORE,JSON.stringify(s));updateDashboard()}
function pct(c,t){return t?Math.round(c/t*100):0}
function currentPackFile(){return activePackFile||packSelect.value}
function qkey(q=questions[current]){return `${currentPackFile()}::${q.id}`}
function updateStats(rec){if(rec.statsSaved)return;let s=getStats();s.answered++;if(rec.correct)s.correct++;if(['guess','50','not selected'].includes(rec.confidence))s.lowConf++;for(let key of ['domain','topic','mistake']){let bucket=key==='domain'?s.domains:key==='topic'?s.topics:s.mistakes;let val=rec[key];if(!val)continue;if(!bucket[val])bucket[val]={answered:0,correct:0};bucket[val].answered++;if(rec.correct)bucket[val].correct++;}rec.statsSaved=true;saveStats(s)}
function weakest(obj){let name='Start Pack 1',min=101;Object.entries(obj).forEach(([k,v])=>{if(v.answered>=2){let p=pct(v.correct,v.answered);if(p<min){min=p;name=k}}});return name}
function updateDashboard(){let s=getStats(),acc=pct(s.correct,s.answered),readiness=Math.min(99,Math.round(acc*.75+Math.min(s.answered,100)*.25));dashAnswered.textContent=s.answered;dashAccuracy.textContent=acc+'%';dashLowConf.textContent=s.lowConf;readinessScore.textContent=readiness+'%';readinessLabel.textContent=readiness>=85?'Strong readiness':readiness>=70?'Building readiness':'Start practicing';dashFocus.textContent=weakest(s.domains)}
async function init(){updateDashboard();manifest=await fetch('questions/manifest.json').then(r=>r.json());manifest.packs.forEach(p=>{let o=document.createElement('option');o.value=p.file;o.textContent=`${p.title} (${p.count})`;packSelect.appendChild(o)});examBank=(await Promise.all(EXAM_PACKS.map(file=>fetch(file).then(r=>r.json()).catch(()=>[])))).flat();let l=getLists();flagged=new Set(l.flagged);favorites=new Set(l.favorites);await loadSelectedPack()}
async function loadSelectedPack(){appView='academy';activePackFile=packSelect.value;sourceQuestions=await fetch(packSelect.value).then(r=>r.json());prepareAttempt();restart()}
function setMode(m){mode=m;prepareAttempt();restart()}
function setAppView(v){appView=v;updateTopMenu();if(v==='academy'){academyToolbar.style.display='flex';examPanel.innerHTML='';if(!questions.length||currentPackFile()===EXAM_PACK)loadSelectedPack();else render()}else if(v==='exam'){academyToolbar.style.display='none';renderExamHome()}else renderDashboardView()}
function updateTopMenu(){academyMenuBtn.className=appView==='academy'?'':'secondary';examMenuBtn.className=appView==='exam'?'':'secondary';dashboardMenuBtn.className=appView==='dashboard'?'':'secondary'}
function randomizeArray(arr){return ExamEngine.fisherYates(arr)}
function startExamSimulator(type){appView='exam';updateTopMenu();academyToolbar.style.display='none';activePackFile=EXAM_PACK;let pool=[...examBank];if(type==='pbq')pool=pool.filter(isPbq);if(type==='missed'){let missed=new Set((getLists().incorrect||[]).filter(k=>k.startsWith(EXAM_PACK)).map(k=>k.split('::').pop()));pool=pool.filter(q=>missed.has(String(q.id)))}if(!pool.length){examPanel.innerHTML='<div class="reviewList"><h2>Exam Simulator</h2><p class="small">No questions are available for that option yet. Try Quick Quiz or Standard Set.</p></div>';return}let count=typeof type==='number'?type:type==='quick'?10:type==='standard'?25:pool.length;sourceQuestions=ExamEngine.generateExam(pool,count);mode='exam';restart()}
function renderExamHome(){updateTopMenu();academyToolbar.style.display='none';modebar.style.display='none';controls.style.display='none';caseSelection.innerHTML='';caseIntro.innerHTML='';progress.textContent='';score.textContent='';meta.textContent='';modeBadge.textContent='';question.textContent='Exam Simulator';question.className='question';options.innerHTML='';explanation.innerHTML='';confidenceBox.style.display='none';submitBtn.style.display='none';finalAnalytics.innerHTML='';sideNavigator.innerHTML='';examPanel.innerHTML=`<div class="exam-home"><h2>Exam Simulator</h2><p class="small">Choose an exam length. Questions and answer choices are fixed for the entire attempt, and results stay hidden until submission.</p><div class="exam-actions"><button onclick="startExamSimulator(10)">Quick Quiz: 10 questions</button><button onclick="startExamSimulator(25)">Standard Set: 25 questions</button><button onclick="startExamSimulator(50)">Long Set: 50 questions</button><button onclick="startExamSimulator(85)">Full Exam: 85 questions</button><button class="secondary" onclick="startExamSimulator('pbq')">PBQ Practice</button><button class="secondary" onclick="startExamSimulator('missed')">Review Missed</button></div></div>`}
function caseKey(q){return q.case_file||'Standalone Practice'}
function caseInfo(key,items){let fallbackTitle=key==='Standalone Practice'?'Standalone Questions':key;let derivedDifficulty=[...new Set(items.map(q=>q.difficulty).filter(Boolean))].join(' / ')||'Mixed';return CASE_DETAILS[key]||{number:key,title:fallbackTitle.replace(/^Case \d+:?\s*/,''),difficulty:derivedDifficulty,scenario:'Practice questions in this pack are grouped together for a focused review session.',context:'Read the question details carefully and use the explanation after submission to reinforce the key learning point.'}}
function groupedCases(){let groups=[];sourceQuestions.forEach(q=>{let key=caseKey(q);let group=groups.find(g=>g.key===key);if(!group){group={key,questions:[]};groups.push(group)}group.questions.push(q)});return groups.map(g=>({...g,info:caseInfo(g.key,g.questions)}))}
function renderCaseSelection(){if(!window.caseSelection)return;if(appView!=='academy'){caseSelection.innerHTML='';return}let groups=groupedCases();let html='<h2>Case Selection</h2><p class="small">This pack keeps case-file questions grouped so you can work through each investigation in order.</p><div class="case-grid">';groups.forEach(g=>{html+=`<button class="case-select-card" onclick="jumpTo(${firstIndexForCase(g.key)})"><span>${g.info.number}</span><strong>${g.info.title}</strong><em>${g.info.difficulty}</em><small>${g.questions.length} question${g.questions.length===1?'':'s'}</small></button>`});caseSelection.innerHTML=html+'</div>'}
function firstIndexForCase(key){return questions.findIndex(q=>caseKey(q)===key)}
function renderCaseIntro(q){if(!window.caseIntro)return;if(appView!=='academy'){caseIntro.innerHTML='';return}let key=caseKey(q),first=questions.findIndex(x=>caseKey(x)===key);if(current!==first){caseIntro.innerHTML='';return}let info=caseInfo(key,questions.filter(x=>caseKey(x)===key));caseIntro.innerHTML=`<section class="case-intro"><div><span class="case-number">${info.number}</span><h2>${info.title}</h2></div><span class="case-difficulty">${info.difficulty}</span><p><strong>Scenario introduction:</strong> ${info.scenario}</p><p><strong>Investigation context:</strong> ${info.context}</p></section>`}
function prepareAttempt(){questions=ExamEngine.balanceQuestionOptions(sourceQuestions.map(normalizeQuestion))}
function normalizeQuestion(q){let concept=(q.concept_tags||[]).join(', ');return {...q,qtype:q.qtype||q.question_type||q.kind,topic:q.topic||concept||'Exam Objective',why_correct:q.why_correct||q.explanation||'',takeaway:q.takeaway||q.exam_tip||'',trap:q.trap||q.exam_tip||'Read the wording carefully.',mistake_type:q.mistake_type||concept}}
function randomizeQuestionOptions(q){return ExamEngine.balanceQuestionOptions([q])[0]}
function isPbq(q){return ((q.qtype||q.question_type||'')+' '+(q.topic||'')).toUpperCase().includes('PBQ')}
function secondBest(q){if(q.second_best)return q.second_best;if(q.why_wrong){let idx=Object.keys(q.why_wrong)[0];if(idx!==undefined)return `${q.options[parseInt(idx)]}: ${q.why_wrong[idx]}`}return q.trap||'The tempting choice usually overstates what the evidence proves or skips a required investigation step.'}
function keyClue(q){if(q.key_clue)return q.key_clue;let text=q.question.split('\n').filter(x=>x.trim().startsWith('-')||/Defender|DNS|proxy|internet-facing|active exploitation|isolated|quarantined|CVSS|ransomware/i.test(x)).slice(0,2).join(' ');return text||'The most important clue is the evidence that directly supports scope, impact, or the requested next action.'}
function updateSelectedOptionStyles(){document.querySelectorAll('#options .option').forEach(l=>{let input=l.querySelector('input');let selected=!!input?.checked;l.classList.toggle('selected',selected);let pill=l.querySelector('.selected-pill');if(selected&&!pill){let span=document.createElement('span');span.className='selected-pill';span.textContent='Selected';l.appendChild(span)}if(!selected&&pill)pill.remove()})}
function saveOptionDraft(){if(answers[current]?.submitted||answers[current]?.graded)return;let sel=selectedNow(),conf=getConf();answers[current]={...(answers[current]||{}),selected:sel,confidence:conf};renderNavigator()}
function render(){updateTopMenu();if(appView==='dashboard'){renderDashboardView();return}if(appView==='exam'){academyToolbar.style.display='none';modebar.style.display='flex';controls.style.display='flex';examPanel.innerHTML=''}else{academyToolbar.style.display='flex';modebar.style.display='flex';controls.style.display='flex';examPanel.innerHTML=''}let q=questions[current],st=answers[current];renderCaseSelection();renderCaseIntro(q);progress.textContent=`Question ${current+1} / ${questions.length}`;score.textContent=mode==='exam'?'':`Score: ${sessionScore}`;meta.textContent=mode==='exam'?(isPbq(q)?'Performance-Based Question':''):`${q.domain} • ${q.qtype||q.kind} • ${q.difficulty}`;modeBadge.textContent=mode==='practice'?'Practice Mode':'Exam Mode';question.textContent=q.question;question.className=isPbq(q)?'question pbq-question':'question';options.innerHTML='';explanation.innerHTML='';finalAnalytics.innerHTML='';submitBtn.style.display=mode==='practice'&&!st?.submitted?'inline-block':'none';confidenceBox.style.display='block';document.querySelectorAll('input[name=confidence]').forEach(x=>x.checked=st?.confidence===x.value);if(isPbq(q)){let pbq=document.createElement('div');pbq.className='pbq-banner';pbq.innerHTML='<strong>Performance-Based Question</strong><span>Use the same answer controls, but treat this like an evidence-ordering or triage task.</span>';options.appendChild(pbq)}q.options.forEach((opt,idx)=>{let l=document.createElement('label');l.className=isPbq(q)?'option pbq-option':'option';let t=q.kind==='multi'?'checkbox':'radio';l.innerHTML=`<input type="${t}" name="answer" value="${idx}" style="margin-right:10px;">${opt}`;let input=l.querySelector('input');if(st?.selected?.includes(idx))input.checked=true;input.addEventListener('change',()=>{if(q.kind==='multi')enforceSelectLimit(q.select_limit);updateSelectedOptionStyles();saveOptionDraft()});if(st?.submitted||st?.graded){if(q.answer.includes(idx))l.classList.add('correct');if(st.selected?.includes(idx)&&!q.answer.includes(idx))l.classList.add('wrong');input.disabled=true}options.appendChild(l)});if(q.kind==='multi'){let note=document.createElement('p');note.className='small warn';note.textContent=`Select exactly ${q.select_limit}.`;options.prepend(note)}updateSelectedOptionStyles();if((st?.submitted&&mode==='practice')||st?.graded)showExplanation(q,st.correct,st.confidence,false);renderNavigator()}
function enforceSelectLimit(limit){let checked=[...document.querySelectorAll('#options input[type=checkbox]:checked')];if(checked.length>limit){checked[checked.length-1].checked=false;alert(`Select only ${limit}.`)}}
function selectedNow(){let q=questions[current],sel=[];let selector=q.kind==='multi'?'#options input[type=checkbox]:checked':'#options input[name=answer]:checked';document.querySelectorAll(selector).forEach(x=>sel.push(parseInt(x.value)));return sel}
function getConf(){let c=document.querySelector('input[name=confidence]:checked');return c?c.value:'not selected'}
function arraysEqual(a,b){return JSON.stringify([...a].sort((x,y)=>x-y))===JSON.stringify([...b].sort((x,y)=>x-y))}
function saveCurrentDraft(){if(answers[current]?.submitted||answers[current]?.graded)return;let sel=selectedNow(),conf=getConf();answers[current]={...(answers[current]||{}),selected:sel,confidence:conf}}
function submitAnswer(){let q=questions[current],sel=selectedNow();if(q.kind==='multi'&&sel.length!==q.select_limit){alert(`Please select exactly ${q.select_limit}.`);return}if(q.kind==='single'&&sel.length!==1){alert('Please select one answer.');return}let correct=arraysEqual(sel,q.answer),conf=getConf();answers[current]={selected:sel,confidence:conf,correct,submitted:true,graded:true};if(correct)sessionScore++;updateStats({domain:q.domain,topic:q.topic||'',mistake:correct?'':q.mistake_type,correct,confidence:conf});if(!correct){let l=getLists();if(!l.incorrect.includes(qkey()))l.incorrect.push(qkey());saveLists(l)}render()}
function gradeExam(){sessionScore=0;questions.forEach((q,i)=>{let st=answers[i]||{selected:[],confidence:'not selected'};let correct=arraysEqual(st.selected||[],q.answer);answers[i]={...st,correct,graded:true,submitted:true};if(correct)sessionScore++;updateStats({domain:q.domain,topic:q.topic||'',mistake:correct?'':q.mistake_type,correct,confidence:st.confidence||'not selected'});if(!correct){let l=getLists(),key=`${currentPackFile()}::${q.id}`;if(!l.incorrect.includes(key))l.incorrect.push(key);saveLists(l)}})}
function showExplanation(q,correct,conf){let h=`<div class="explanation"><strong>${correct?'Correct':'Not quite'}.</strong> Confidence: <strong>${conf}</strong><br><br>`;h+=`<strong>Correct answer${q.answer.length>1?'s':''}:</strong> ${q.answer.map(i=>q.options[i]).join('; ')}<br><br><strong>Why the correct answer is correct:</strong><br>${q.why_correct}<br><br><strong>Why the second-best answer was tempting:</strong><br>${secondBest(q)}<br><br><strong>Scenario clue that mattered most:</strong><br>${keyClue(q)}<br><br><strong>CompTIA trap:</strong><br>${q.trap}<br><br><strong>Exam takeaway:</strong><br>${q.takeaway}`;if(!correct&&q.mistake_type)h+=`<div class="coach"><strong>Coach note:</strong><br>This miss may indicate: ${q.mistake_type}.</div>`;if(q.why_wrong){h+='<br><br><strong>Why the other answers are wrong:</strong><ul>';for(let [idx,reason] of Object.entries(q.why_wrong))h+=`<li><strong>${q.options[parseInt(idx)]}:</strong> ${reason}</li>`;h+='</ul>'}explanation.innerHTML=h+'</div>'}
function nextQuestion(){saveCurrentDraft();if(current<questions.length-1){current++;render()}else finish()}
function prevQuestion(){saveCurrentDraft();if(current>0){current--;render()}}
function jumpTo(i){saveCurrentDraft();current=i;render()}
function toggleFlag(){let k=qkey();flagged.has(k)?flagged.delete(k):flagged.add(k);persistLists();renderNavigator()}
function toggleFavorite(){let k=qkey();favorites.has(k)?favorites.delete(k):favorites.add(k);persistLists();renderNavigator()}
function persistLists(){let l=getLists();l.flagged=[...flagged];l.favorites=[...favorites];saveLists(l)}
function renderNavigator(){let html='';questions.forEach((q,i)=>{let key=`${currentPackFile()}::${q.id}`,st=answers[i]||{},cls='navBtn',isSubmitted=!!(st.submitted||st.graded),hasSelection=!!(st.selected&&st.selected.length);if(isSubmitted)cls+=' navAnswered';else if(hasSelection)cls+=' navSelected';if(flagged.has(key))cls+=' navFlagged';if(favorites.has(key))cls+=' navFavorite';if(st.graded&&!st.correct&&!(mode==='exam'&&appView==='exam'))cls+=' navIncorrect';if(i===current)cls+=' navCurrent';if(isPbq(q))cls+=' navPbq';let icons=(isSubmitted?'✓ ':(hasSelection?'○ ':''))+(flagged.has(key)?'⚑ ':'')+(favorites.has(key)?'⭐ ':'')+(st.graded&&!st.correct&&!(mode==='exam'&&appView==='exam')?'❌ ':'')+(isPbq(q)?'PBQ ':'');html+=`<button class="${cls}" onclick="jumpTo(${i})">Q${i+1} ${icons}<br><span class="small">${q.topic}</span></button>`});sideNavigator.innerHTML=html}
function showStudyList(type){let l=getLists(),arr=l[type]||[],title=type==='flagged'?'Flagged Questions':type==='incorrect'?'Incorrect Questions':'Favorite Questions';let html=`<div class="reviewList"><h2>${title}</h2>`;if(!arr.length)html+='<p class="small">Nothing saved here yet.</p>';arr.forEach(k=>{let id=k.split('::').pop();let q=questions.find(x=>String(x.id)===String(id));if(q)html+=`<div class="reviewItem"><span><strong>Q${questions.indexOf(q)+1}</strong> — ${q.topic}<br><span class="small">${q.domain}</span></span><button onclick="jumpTo(${questions.indexOf(q)})">Review</button></div>`});finalAnalytics.innerHTML=html+'</div>'}
function finish(){saveCurrentDraft();if(mode==='exam'){gradeExam();mode='review'}caseIntro.innerHTML='';question.textContent=`Session complete! Score: ${sessionScore} / ${questions.length}`;question.className='question';options.innerHTML='';explanation.innerHTML='';confidenceBox.style.display='none';submitBtn.style.display='none';let by={},objectives={},missed=[],letters=Object.fromEntries(ExamEngine.LETTERS.map(l=>[l,0]));questions.forEach((q,i)=>{let st=answers[i]||{};if(!by[q.domain])by[q.domain]={t:0,c:0};by[q.domain].t++;if(st.correct)by[q.domain].c++;(q.concept_tags||[q.topic||'General']).forEach(objective=>{if(!objectives[objective])objectives[objective]={t:0,c:0};objectives[objective].t++;if(st.correct)objectives[objective].c++});q.answer.forEach(index=>{if(ExamEngine.LETTERS[index])letters[ExamEngine.LETTERS[index]]++});if(!st.correct)missed.push({q,i})});let flaggedItems=questions.map((q,i)=>({q,i,key:`${currentPackFile()}::${q.id}`})).filter(item=>flagged.has(item.key));let html='<div class="analytics review-summary"><h2>Exam Summary</h2><div class="summary-grid">';html+=`<div class="metric"><strong>Overall Score</strong><br>${sessionScore}/${questions.length} (${pct(sessionScore,questions.length)}%)</div><div class="metric"><strong>Flagged</strong><br>${flaggedItems.length}</div><div class="metric"><strong>Missed</strong><br>${missed.length}</div>`;html+='</div><div class="review-section"><h3>Domain Scores</h3>'+Object.entries(by).map(([d,v])=>`<div class="reviewItem"><span>${d}</span><strong>${v.c}/${v.t} (${pct(v.c,v.t)}%)</strong></div>`).join('')+'</div>';html+='<div class="review-section"><h3>Objective Scores</h3>'+Object.entries(objectives).map(([o,v])=>`<div class="reviewItem"><span>${o}</span><strong>${v.c}/${v.t} (${pct(v.c,v.t)}%)</strong></div>`).join('')+'</div>';let reviewItems=items=>items.length?items.map(m=>`<div class="reviewItem"><span><strong>Q${m.i+1}</strong> — ${m.q.topic}<br><span class="small">${m.q.domain}</span></span><button onclick="jumpTo(${m.i})">Review</button></div>`).join(''):'<p class="small">None.</p>';html+=`<div class="review-section"><h3>Missed Questions</h3>${reviewItems(missed)}</div><div class="review-section"><h3>Flagged Questions</h3>${reviewItems(flaggedItems)}</div>`;html+='<div class="review-section"><h3>Correct Answer-Letter Distribution</h3><div class="summary-grid">'+Object.entries(letters).map(([letter,count])=>`<div class="metric"><strong>${letter}</strong><br>${count}</div>`).join('')+'</div></div></div>';finalAnalytics.innerHTML=html;score.textContent=`Score: ${sessionScore} / ${questions.length}`;meta.textContent='Review available';renderNavigator()}
function restart(){current=0;sessionScore=0;answers={};prepareAttempt();if(questions.length)render()}
function shuffleQuiz(){let grouped=groupedCases().map(g=>sourceQuestions.filter(q=>caseKey(q)===g.key));sourceQuestions=randomizeArray(grouped).flatMap(group=>group);restart()}
function renderDashboardView(){appView='dashboard';updateTopMenu();academyToolbar.style.display='none';modebar.style.display='none';controls.style.display='none';examPanel.innerHTML='';caseSelection.innerHTML='';caseIntro.innerHTML='';progress.textContent='';score.textContent='';meta.textContent='';modeBadge.textContent='';options.innerHTML='';explanation.innerHTML='';confidenceBox.style.display='none';submitBtn.style.display='none';sideNavigator.innerHTML='';let s=getStats(),domains=Object.entries(s.domains||{}),mistakes=Object.entries(s.mistakes||{}).sort((a,b)=>b[1].answered-a[1].answered).slice(0,5),pbqAnswered=0,pbqCorrect=0;Object.entries(s.topics||{}).forEach(([k,v])=>{if(k.toUpperCase().includes('PBQ')){pbqAnswered+=v.answered;pbqCorrect+=v.correct}});question.textContent='Dashboard';question.className='question';let recent=s.answered?`${s.answered} combined Analyst Academy / Exam Simulator attempts with ${pct(s.correct,s.answered)}% accuracy.`:'No recent activity yet. Start Analyst Academy or Exam Simulator.';finalAnalytics.innerHTML=`<div class="analytics dashboard-mvp"><h2>Dashboard MVP</h2><p class="small">Analyst Academy and Exam Simulator currently share combined localStorage attempt stats; saved missed items stay namespaced by pack.</p><div class="summary-grid"><div class="metric"><strong>Combined Accuracy</strong><br>${pct(s.correct,s.answered)}%</div><div class="metric"><strong>Combined Answered</strong><br>${s.answered}</div><div class="metric"><strong>PBQ Performance</strong><br>${pbqAnswered?`${pbqCorrect}/${pbqAnswered} (${pct(pbqCorrect,pbqAnswered)}%)`:'No PBQs answered yet'}</div></div><div class="dashboard-section"><h3>Domain Performance</h3>${domains.length?domains.map(([d,v])=>`<div class="reviewItem"><span>${d}</span><strong>${v.correct}/${v.answered} (${pct(v.correct,v.answered)}%)</strong></div>`).join(''):'<p class="small">No domain data yet.</p>'}</div><div class="dashboard-section"><h3>Weak Concepts</h3>${mistakes.length?'<ul>'+mistakes.map(([m,v])=>`<li>${m}: ${v.answered-v.correct} miss${v.answered-v.correct===1?'':'es'} / ${v.answered} attempts</li>`).join('')+'</ul>':'<p class="small">No weak concepts identified yet.</p>'}</div><div class="dashboard-section"><h3>Recent Activity</h3><p>${recent}</p></div><div class="coach"><strong>Study recommendation:</strong><br>${s.answered?'Focus on the lowest-scoring domain above, then run a Quick Quiz.':'Start with Analyst Academy Case File 001, then try a Quick Quiz.'}</div></div>`}
function resetProgress(){if(confirm('Reset saved progress and lists?')){localStorage.removeItem(STORE);localStorage.removeItem(LISTS);flagged=new Set();favorites=new Set();updateDashboard();restart()}}
init();
