let manifest=null,questions=[],current=0,sessionScore=0,results=[],flagged=new Set(),favorites=new Set(),answers={};
const STORE='cysaCoachRelease2Stats', LISTS='cysaCoachRelease2Lists';
function getStats(){return JSON.parse(localStorage.getItem(STORE)||'{"answered":0,"correct":0,"lowConf":0,"domains":{},"topics":{},"mistakes":{}}')}
function getLists(){return JSON.parse(localStorage.getItem(LISTS)||'{"flagged":[],"incorrect":[],"favorites":[]}' )}
function saveLists(l){localStorage.setItem(LISTS,JSON.stringify(l))}
function saveStats(s){localStorage.setItem(STORE,JSON.stringify(s));updateDashboard()}
function pct(c,t){return t?Math.round(c/t*100):0}
function updateStats(r){let s=getStats();s.answered++;if(r.correct)s.correct++;if(['guess','50','not selected'].includes(r.confidence))s.lowConf++;for(let key of ['domain','topic','mistake']){let bucket=key==='domain'?s.domains:key==='topic'?s.topics:s.mistakes;let val=r[key];if(!val)continue;if(!bucket[val])bucket[val]={answered:0,correct:0};bucket[val].answered++;if(r.correct)bucket[val].correct++;}saveStats(s)}
function weakest(obj){let name='Start Pack 1',min=101;Object.entries(obj).forEach(([k,v])=>{if(v.answered>=2){let p=pct(v.correct,v.answered);if(p<min){min=p;name=k}}});return name}
function updateDashboard(){let s=getStats();let acc=pct(s.correct,s.answered);let readiness=Math.min(99,Math.round(acc*.75+Math.min(s.answered,100)*.25));dashAnswered.textContent=s.answered;dashAccuracy.textContent=acc+'%';dashLowConf.textContent=s.lowConf;readinessScore.textContent=readiness+'%';readinessLabel.textContent=readiness>=85?'Strong readiness':readiness>=70?'Building readiness':'Start practicing';dashFocus.textContent=weakest(s.domains)}
async function init(){updateDashboard();manifest=await fetch('questions/manifest.json').then(r=>r.json());manifest.packs.forEach(p=>{let o=document.createElement('option');o.value=p.file;o.textContent=`${p.title} (${p.count})`;packSelect.appendChild(o)});let l=getLists();flagged=new Set(l.flagged);favorites=new Set(l.favorites);await loadSelectedPack()}
async function loadSelectedPack(){questions=await fetch(packSelect.value).then(r=>r.json());restart()}
function qkey(q=questions[current]){return `${packSelect.value}::${q.id}`}
function persistLists(){let l=getLists();l.flagged=[...flagged];l.favorites=[...favorites];saveLists(l)}
function render(){let q=questions[current];progress.textContent=`Question ${current+1} / ${questions.length}`;score.textContent=`Score: ${sessionScore}`;meta.textContent=`${q.domain} • ${q.qtype||q.kind} • ${q.difficulty}`;question.textContent=q.question;options.innerHTML='';explanation.innerHTML='';finalAnalytics.innerHTML='';submitBtn.style.display='inline-block';confidenceBox.style.display='block';document.querySelectorAll('input[name=confidence]').forEach(x=>x.checked=false);if(q.kind==='single'||q.kind==='multi'){q.options.forEach((opt,idx)=>{let l=document.createElement('label');l.className='option';let t=q.kind==='multi'?'checkbox':'radio';l.innerHTML=`<input type="${t}" name="answer" value="${idx}" style="margin-right:10px;">${opt}`;let input=l.querySelector('input');if(answers[current]?.selected?.includes(idx))input.checked=true;if(q.kind==='multi')input.addEventListener('change',()=>enforceSelectLimit(q.select_limit));options.appendChild(l)});if(q.kind==='multi'){let note=document.createElement('p');note.className='small warn';note.textContent=`Select exactly ${q.select_limit}.`;options.prepend(note)}}renderNavigator()}
function enforceSelectLimit(limit){let checked=[...document.querySelectorAll('#options input[type=checkbox]:checked')];if(checked.length>limit){checked[checked.length-1].checked=false;alert(`Select only ${limit}.`)}}
function arraysEqual(a,b){return JSON.stringify([...a].sort((x,y)=>x-y))===JSON.stringify([...b].sort((x,y)=>x-y))}
function getConf(){let c=document.querySelector('input[name=confidence]:checked');return c?c.value:'not selected'}
function selectedNow(){let q=questions[current], sel=[];let selector=q.kind==='multi'?'#options input[type=checkbox]:checked':'#options input[name=answer]:checked';document.querySelectorAll(selector).forEach(x=>sel.push(parseInt(x.value)));return sel}
function toggleFlag(){let k=qkey();flagged.has(k)?flagged.delete(k):flagged.add(k);persistLists();renderNavigator();alert(flagged.has(k)?'Flagged for review':'Removed flag')}
function toggleFavorite(){let k=qkey();favorites.has(k)?favorites.delete(k):favorites.add(k);persistLists();alert(favorites.has(k)?'Added to favorites':'Removed favorite')}
function submitAnswer(){let q=questions[current],correct=false,sel=selectedNow();if(q.kind==='multi'&&sel.length!==q.select_limit){alert(`Please select exactly ${q.select_limit}.`);return}if(q.kind==='single'&&sel.length!==1){alert('Please select one answer.');return}correct=arraysEqual(sel,q.answer);answers[current]={selected:sel,correct};document.querySelectorAll('#options .option').forEach((lab,idx)=>{if(q.answer.includes(idx))lab.classList.add('correct');if(sel.includes(idx)&&!q.answer.includes(idx))lab.classList.add('wrong')});if(!results.find(r=>r.index===current)){if(correct)sessionScore++;let conf=getConf();let rec={index:current,key:qkey(),domain:q.domain,topic:q.topic||'',type:q.qtype||q.kind,mistake:correct?'':q.mistake_type,correct,confidence:conf,flagged:flagged.has(qkey())};results.push(rec);if(!correct){let l=getLists();if(!l.incorrect.includes(qkey()))l.incorrect.push(qkey());saveLists(l)}updateStats(rec)}score.textContent=`Score: ${sessionScore}`;showExplanation(q,correct,getConf());submitBtn.style.display='none';renderNavigator()}
function showExplanation(q,correct,conf){let h=`<div class="explanation"><strong>${correct?'Correct':'Not quite'}.</strong> Confidence: <strong>${conf}</strong><br><br>`;h+=`<strong>Correct answer${q.answer.length>1?'s':''}:</strong> ${q.answer.map(i=>q.options[i]).join('; ')}<br><br>`;h+=`<strong>Why the correct answer is correct:</strong><br>${q.why_correct}<br><br><strong>CompTIA trap:</strong><br>${q.trap}<br><br><strong>Takeaway:</strong><br>${q.takeaway}`;if(!correct&&q.mistake_type)h+=`<div class="coach"><strong>Coach note:</strong><br>This miss may indicate: ${q.mistake_type}.</div>`;if(q.why_wrong){h+='<br><br><strong>Why the other answers are wrong:</strong><ul>';for(let [idx,reason] of Object.entries(q.why_wrong))h+=`<li><strong>${q.options[parseInt(idx)]}:</strong> ${reason}</li>`;h+='</ul>'}explanation.innerHTML=h+'</div>'}
function nextQuestion(){if(current<questions.length-1){current++;render()}else finish()}
function prevQuestion(){if(current>0){current--;render()}}
function jumpTo(i){current=i;render();navigator.style.display='none'}
function toggleNavigator(){navigator.style.display=navigator.style.display==='none'?'block':'none';renderNavigator()}
function renderNavigator(){if(!questions.length)return;let html='<strong>Question Navigator</strong><br>';questions.forEach((q,i)=>{let cls='navBtn';if(answers[i])cls+=' navAnswered';if(flagged.has(`${packSelect.value}::${q.id}`))cls+=' navFlagged';if(i===current)cls+=' navCurrent';html+=`<button class="${cls}" onclick="jumpTo(${i})">${i+1}${flagged.has(`${packSelect.value}::${q.id}`)?' ⚑':''}</button>`});navigator.innerHTML=html}
function showStudyList(type){let l=getLists();let arr=l[type]||[];let title=type==='flagged'?'Flagged Questions':type==='incorrect'?'Incorrect Questions':'Favorite Questions';let html=`<div class="reviewList"><h2>${title}</h2>`;if(!arr.length)html+='<p class="small">Nothing saved here yet.</p>';arr.forEach(k=>{let id=k.split('::').pop();let q=questions.find(x=>String(x.id)===String(id));if(q)html+=`<div class="reviewItem"><span><strong>Q${questions.indexOf(q)+1}</strong> — ${q.topic}<br><span class="small">${q.domain}</span></span><button onclick="jumpTo(${questions.indexOf(q)})">Review</button></div>`});html+='</div>';finalAnalytics.innerHTML=html}
function finish(){question.textContent=`Quiz complete! Final score: ${sessionScore} / ${questions.length}`;options.innerHTML='';explanation.innerHTML='';confidenceBox.style.display='none';submitBtn.style.display='none';let by={};results.forEach(r=>{if(!by[r.domain])by[r.domain]={t:0,c:0};by[r.domain].t++;if(r.correct)by[r.domain].c++});let html='<div class="analytics"><h2>Session Report</h2><div class="grid">';html+=`<div class="metric"><strong>Session Score</strong><br>${pct(sessionScore,questions.length)}%</div><div class="metric"><strong>Flagged</strong><br>${[...flagged].filter(k=>k.startsWith(packSelect.value)).length}</div><div class="metric"><strong>Incorrect This Session</strong><br>${results.filter(r=>!r.correct).length}</div>`;Object.entries(by).forEach(([d,v])=>html+=`<div class="metric"><strong>${d}</strong><br>${v.c}/${v.t} (${pct(v.c,v.t)}%)</div>`);html+='</div></div>';finalAnalytics.innerHTML=html;showStudyList('flagged')}
function restart(){current=0;sessionScore=0;results=[];answers={};if(questions.length)render()}
function shuffleQuiz(){questions=[...questions].sort(()=>Math.random()-0.5);restart()}
function resetProgress(){if(confirm('Reset saved progress and saved lists?')){localStorage.removeItem(STORE);localStorage.removeItem(LISTS);flagged=new Set();favorites=new Set();updateDashboard();restart()}}
init();