let manifest=null,questions=[],current=0,score=0,orderState=[],results=[],flagged=new Set();
async function init(){manifest=await fetch('questions/manifest.json').then(r=>r.json());const s=document.getElementById('packSelect');manifest.packs.forEach(p=>{const o=document.createElement('option');o.value=p.file;o.textContent=`${p.title} (${p.count})`;s.appendChild(o)});await loadSelectedPack()}
async function loadSelectedPack(){questions=await fetch(document.getElementById('packSelect').value).then(r=>r.json());restart()}
function shuffled(a){let c=[...a];for(let i=c.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function render(){const q=questions[current];progress.textContent=`Question ${current+1} / ${questions.length}`;scoreEl().textContent=`Score: ${score}`;meta.textContent=`${q.domain} • ${q.qtype||q.kind} • ${q.difficulty}`;question.textContent=q.question;options.innerHTML='';explanation.innerHTML='';finalAnalytics.innerHTML='';submitBtn.style.display='inline-block';nextBtn.style.display='none';confidenceBox.style.display='block';document.querySelectorAll('input[name=confidence]').forEach(x=>x.checked=false);if(q.kind==='single'||q.kind==='multi'){q.options.forEach((opt,idx)=>{const l=document.createElement('label');l.className='option';const t=q.kind==='multi'?'checkbox':'radio';l.innerHTML=`<input type="${t}" name="answer" value="${idx}" style="margin-right:10px;">${opt}`;if(q.kind==='multi')l.querySelector('input').addEventListener('change',()=>enforceSelectLimit(q.select_limit));options.appendChild(l)});if(q.kind==='multi'){const note=document.createElement('p');note.className='small warn';note.textContent=`Select exactly ${q.select_limit}.`;options.prepend(note)}}if(q.kind==='order'){orderState=[...q.items];renderOrder()}}
function scoreEl(){return document.getElementById('score')}
function enforceSelectLimit(limit){const checked=[...document.querySelectorAll('#options input[type=checkbox]:checked')];if(checked.length>limit){checked[checked.length-1].checked=false;alert(`Select only ${limit} answer(s).`)}}
function renderOrder(){options.innerHTML='<p class="small">Use arrows to arrange the steps, then submit.</p>';orderState.forEach((item,idx)=>{const d=document.createElement('div');d.className='orderItem';d.innerHTML=`<span><strong>${idx+1}.</strong> ${item}</span><span><button onclick="moveOrder(${idx},-1)" type="button">↑</button> <button onclick="moveOrder(${idx},1)" type="button">↓</button></span>`;options.appendChild(d)})}
function moveOrder(i,d){const n=i+d;if(n<0||n>=orderState.length)return;[orderState[i],orderState[n]]=[orderState[n],orderState[i]];renderOrder()}
function arraysEqual(a,b){return JSON.stringify([...a].sort((x,y)=>x-y))===JSON.stringify([...b].sort((x,y)=>x-y))}
function getConf(){const c=document.querySelector('input[name=confidence]:checked');return c?c.value:'not selected'}
function toggleFlag(){flagged.has(current)?flagged.delete(current):flagged.add(current);alert(flagged.has(current)?'Flagged for review':'Removed flag')}
function submitAnswer(){const q=questions[current];let correct=false,sel=[];if(q.kind==='single'||q.kind==='multi'){const selector=q.kind==='multi'?'#options input[type=checkbox]:checked':'#options input[name=answer]:checked';document.querySelectorAll(selector).forEach(x=>sel.push(parseInt(x.value)));if(q.kind==='multi'&&sel.length!==q.select_limit){alert(`Please select exactly ${q.select_limit}.`);return}if(q.kind==='single'&&sel.length!==1){alert('Please select one answer.');return}correct=arraysEqual(sel,q.answer);document.querySelectorAll('#options .option').forEach((lab,idx)=>{if(q.answer.includes(idx))lab.classList.add('correct');if(sel.includes(idx)&&!q.answer.includes(idx))lab.classList.add('wrong')})}if(q.kind==='order')correct=JSON.stringify(orderState)===JSON.stringify(q.answer_order);if(correct)score++;const conf=getConf();results.push({domain:q.domain,type:q.qtype||q.kind,correct,confidence:conf,flagged:flagged.has(current)});scoreEl().textContent=`Score: ${score}`;showExplanation(q,correct,conf);submitBtn.style.display='none';nextBtn.style.display='inline-block'}
function showExplanation(q,correct,conf){let h=`<div class="explanation"><strong>${correct?'Correct':'Not quite'}.</strong> Confidence: <strong>${conf}</strong><br><br>`;if(q.kind==='single'||q.kind==='multi')h+=`<strong>Correct answer${q.answer.length>1?'s':''}:</strong> ${q.answer.map(i=>q.options[i]).join('; ')}<br><br>`;if(q.kind==='order')h+=`<strong>Correct order:</strong><ol>${q.answer_order.map(x=>`<li>${x}</li>`).join('')}</ol>`;h+=`<strong>Why the correct answer is correct:</strong><br>${q.why_correct||q.explanation}<br><br><strong>CompTIA trap:</strong><br>${q.trap||''}<br><br><strong>Takeaway:</strong><br>${q.takeaway||''}`;if(q.why_wrong&&Object.keys(q.why_wrong).length>0){h+='<br><br><strong>Why the other answers are wrong:</strong><ul>';for(const [idx,reason] of Object.entries(q.why_wrong))h+=`<li><strong>${q.options[parseInt(idx)]}:</strong> ${reason}</li>`;h+='</ul>'}explanation.innerHTML=h+'</div>'}
function nextQuestion(){current++;if(current>=questions.length){finish();return}render()}
function finish(){question.textContent=`Quiz complete! Final score: ${score} / ${questions.length}`;options.innerHTML='';explanation.innerHTML='';confidenceBox.style.display='none';submitBtn.style.display='none';nextBtn.style.display='none';let by={};results.forEach(r=>{if(!by[r.domain])by[r.domain]={t:0,c:0};by[r.domain].t++;if(r.correct)by[r.domain].c++});let h='<div class="analytics"><h2>Score Report</h2><div class="grid">';h+=`<div class="metric"><strong>Overall</strong><br>${Math.round(score/questions.length*100)}%</div><div class="metric"><strong>Flagged</strong><br>${results.filter(r=>r.flagged).length}</div>`;Object.entries(by).forEach(([d,v])=>h+=`<div class="metric"><strong>${d}</strong><br>${v.c}/${v.t} (${Math.round(v.c/v.t*100)}%)</div>`);finalAnalytics.innerHTML=h+'</div></div>'}
function restart(){current=0;score=0;results=[];flagged=new Set();if(questions.length)render()}function shuffleQuiz(){questions=[...questions].sort(()=>Math.random()-0.5);restart()}init();